{
 "title": "k6 Load Testing Results (Prometheus)",
 "description": "A dashboard for visualizing results from the k6.io load testing tool, using the Prometheus.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "scenario",
    "label": "scenario",
    "query": {
     "query": "label_values(k6_iterations_total, scenario)"
    }
   },
   {
    "name": "domain",
    "label": "domain",
    "query": {
     "query": "label_values(k6_http_reqs, url)"
    }
   },
   {
    "name": "HttpMetricName",
    "label": "HttpMetricName_Trend",
    "query": "blocked,connecting,duration,receiving,sending,tls_handshaking,waiting"
   }
  ]
 },
 "panels": [
  { "title": "Are these Metrics useful?  ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{scenario=\"$scenario\"})",
     "legendFormat": "sum"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Virtual Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "VUs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "Virtual Users" },
    { "expr": "k6_vus_max", "legendFormat": "Max Users" }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{scenario=\"$scenario\"}[1m]))",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "% Failed Checks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_check{outcome=\"fail\"}[$__rate_interval])) / sum(rate(k6_check[$__rate_interval]))",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "Iterations per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_iterations_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_received_total[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(k6_data_sent_total[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (k6_http_reqs_total{scenario=\"${scenario}\", url=~\".*${domain}.*\"})",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Status code (${domain})",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{scenario=\"${scenario}\", url=~\".*${domain}.*\"}) by (status, method)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response time ${HttpMetricName} _p99(avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_http_req_${HttpMetricName}_p99{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"}"
    }
   ]
  },
  {
   "title": "max (${HttpMetricName})_p99",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(k6_http_req_${HttpMetricName}_p99{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "min (${HttpMetricName})_p99",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(k6_http_req_${HttpMetricName}_p99{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "Requests Failed Rate (avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_failed_rate{scenario=\"$scenario\",expected_response=\"true\", url=~\".*${domain}.*\"})"
    }
   ]
  },
  {
   "title": "K6 latency (${HttpMetricName})",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(k6_http_req_${HttpMetricName}_p99{scenario=\"${scenario}\", url=~\".*${domain}.*\"}) ",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Query (${domain})",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{scenario=\"${scenario}\", url=~\".*${domain}.*\"}) by (url, status)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}