{
 "title": "NGSA - Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "region",
    "query": {
     "query": "label_values(NgsaAppSummary{}, region)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(NgsaAppSummary{}, job)"
    }
   },
   {
    "name": "mode",
    "query": "read:Direct|Query,write:Upsert|Delete"
   }
  ]
 },
 "panels": [
  {
   "title": "NGSA Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ngsa\", phase=\"Running\",pod=~\"$service.*\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ngsa\", phase=\"Pending\",pod=~\"$service.*\"}) ",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$service.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "LodeRunner Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"loderunner\",phase=\"Running\",pod=~\"loderunner.*\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"loderunner\", phase=\"Pending\",pod=~\"loderunner.*\"}) ",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"loderunner\",pod=~\"loderunner.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HPA - NGSA",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"ngsa\",horizontalpodautoscaler=\"ngsa-memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_bucket{region=~\"$region\",job=~\"$service.*\",mode=~\"$mode\"}[5m])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Avg RPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_count{region=~\"$region\",job=~\"$service.*\",mode=~\"$mode\"}[5m]))"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(NgsaAppSummary{code=\"OK\",job=~\"$service.*\",region=~\"$region\",mode=~\"$mode\",quantile=~\"0.95|0.99\"}) by (mode, quantile)",
     "legendFormat": "P {{quantile}} {{mode}}"
    }
   ]
  },
  {
   "title": "LodeRunner Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(LodeRunnerSummary{code=\"OK\",server=~\".*$service.*\",mode=~\"$mode\",quantile=~\"0.95|0.99\"}) by (mode, quantile)",
     "legendFormat": "P {{quantile}} {{mode}}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_count{region=~\"$region\",service=~\"$service.*\",code=~\"Warn|Error\",mode=~\"$mode\"}[1m]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Retry Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_count{region=~\"$region\",service=~\"$service.*\",code = \"Retry\"}[1m]))",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}